version: '3'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=todo_app
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - todo-network

  postgres:
    image: postgres:14-alpine
    container_name: todo-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: todo-pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    depends_on:
      - postgres
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres_data: